__version__ = "1.1.0"

from .transformations.butter_fingers_perturbation.transformation import ButterFingersPerturbation
from .transformations.back_translation.transformation import BackTranslation
from .transformations.change_char_case.transformation import ChangeCharCase
from .transformations.english_inflectional_variation.transformation import EnglishInflectionalVariation
from .transformations.swap_characters.transformation import SwapCharactersPerturbation
from .transformations.synonym_insertion.transformation import SynonymInsertion
from .transformations.synonym_substitution.transformation import SynonymSubstitution
from .transformations.tense.transformation import TenseTransformation, TenseTransformationPast, TenseTransformationFuture
from .transformations.whitespace_perturbation.transformation import WhitespacePerturbation

from .process_docstring import sep_doc, word_blacklist, preprocess_docstring, postprocess_docstring

# from interfaces.SentenceOperation import SentenceOperation
# from interfaces.QuestionAnswerOperation import QuestionAnswerOperation
# from evaluation.evaluation_engine import evaluate, execute_model
# from tasks.TaskTypes import TaskType